# Generated by Django 5.2.1 on 2025-10-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('nota_media', models.FloatField(default=0.0)),
                ('numero_avaliacoes', models.PositiveIntegerField(default=0)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
            ],
            options={
                'unique_together': {('nome', 'endereco', 'categoria', 'telefone')},
            },
        ),
    ]
